"""create_users_table

Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=255)),
    sa.Column('img_id', sa.Integer()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable = False),
    sa.Column("movie_id", sa.Integer, nullable = False),
    sa.Column("title",sa.String(length=255), nullable=False),
    sa.Column("num_reviews", sa.Integer()),
    sa.Column("star_count", sa.Integer()),
    sa.Column("avg_star_rating", sa.Integer()),
    sa.Column("description", sa.String(length=255), nullable=False),
    sa.Column("poster_path", sa.String(length=255)),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id')
    )
    op.create_table("ranked_lists",
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable = False),
    sa.Column('movie_id', sa.Integer()),
    sa.Column("name", sa.String(length=255)),
    sa.Column("movies", sa.String(length=255)),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable = False),
    sa.Column("user_id", sa.Integer, nullable = False),
    sa.Column("movie_id",sa.Integer, nullable = False),
    sa.Column("username", sa.String(length=255)),
    sa.Column("review", sa.String(length=255), nullable=False),
    sa.Column("stars", sa.Integer, nullable = False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table("images",
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageable_id', sa.Integer(), nullable = False),
    sa.Column('imageable_type', sa.String(255), nullable = False),
    sa.Column('url', sa.String(255), nullable = False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table("posts", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(255), nullable=False),
    sa.Column('post_text', sa.String(255), nullable=False),
    sa.Column('likes', sa.Integer(), default=0),
    sa.Column('users_liked', sa.String(255)),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'],),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table("comments", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer, nullable=False),
    sa.Column('username', sa.String(255), nullable=False),
    sa.Column('comment_id', sa.Integer),
    sa.Column('comment_text', sa.String(255), nullable=False),
    sa.Column('likes', sa.Integer(), default=0),
    sa.Column('users_liked', sa.String(255)),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'],),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'],),
    sa.PrimaryKeyConstraint('id'),
    )
    

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE movies SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE ranked_lists SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE images SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('ranked_lists')
    op.drop_table('reviews')
    op.drop_table('posts')
    op.drop_table('images')
    # ### end Alembic commands ###
